#!/usr/bin/env bash

# Ask for the administrator password upfront
sudo -v

# Install PHP 5.6
curl -s http://php-osx.liip.ch/install.sh | bash -s 5.6

ini=/usr/local/php5/php.d/99-liip-developer.ini
github=https://github.com/mourawaldson

# Backup ini
sudo cp $ini $ini-bkp

# Change timezone
sudo sed -i '' 's/Zurich/Recife/g' $ini
sudo sed -i '' 's/Europe/America/g' $ini
sudo sed -i '' '15 s/^/; /g' $ini
sudo sed -i '' '16 s/^/; /g' $ini

# Enable extensions
for i in {54..79}
do
  command="sudo sed -i '' '$i s/; //g' $ini"
  eval="$command"
done

# Install .dotfiles
cd $HOME;
curl -sL $github/dotfiles/tarball/master | tar -xzv --strip-components 1 --exclude=readme.md

# Install command line
xcode-select --install

# Install CCleaner
curl -k -o ccleaner.dmg https://download.piriform.com/mac/CCMacSetup109.dmg && hdiutil attach ccleaner.dmg && cp -R /Volumes/CCleaner/CCleaner.app /Applications/ && hdiutil detach /Volumes/CCleaner && rm CCMacSetup109.dmg

# Install Transmission
curl -O https://transmission.cachefly.net/Transmission-2.84.dmg && hdiutil attach Transmission-2.84.dmg && cp -R /Volumes/Transmission/Transmission.app /Applications/ && hdiutil detach /Volumes/Transmission && rm Transmission-2.84.dmg

# Install VLC
curl -O http://mirror.csclub.uwaterloo.ca/vlc/vlc/2.2.0/macosx/vlc-2.2.0.dmg && hdiutil attach vlc-2.2.0.dmg && cp -R /Volumes/vlc-2.2.0/VLC.app /Applications/ && hdiutil detach /Volumes/vlc-2.2.0 && rm vlc-2.2.0.dmg

# Install DiffMerge
curl -o DiffMerge.dmg http://download-us.sourcegear.com/DiffMerge/4.2.0/DiffMerge.4.2.0.697.intel.stable.dmg && hdiutil attach DiffMerge.dmg && cp -R /Volumes/DiffMerge\ 4.2.0.697\ intel\ stable/DiffMerge.app /Applications/ && hdiutil detach /Volumes/DiffMerge\ 4.2.0.697\ intel\ stable && rm DiffMerge.dmg

# Install MacKeeper
curl -o MacKeeper.2.17.1.pkg http://download.mackeeper.com/package.php?bundleId=29_2 && open MacKeeper.2.17.1.pkg
