#!/usr/bin/env bash

# Ask for the administrator password upfront
sudo -v

# Install PHP 5.6
curl -s http://php-osx.liip.ch/install.sh | bash -s 5.6

ini=/usr/local/php5/php.d/99-liip-developer.ini
github=https://github.com/mourawaldson

# Backup ini
sudo cp $ini $ini-bkp

# Change timezone
sudo sed -i '' 's/Zurich/Recife/g' $ini
sudo sed -i '' 's/Europe/America/g' $ini
sudo sed -i '' '15 s/^/; /g' $ini
sudo sed -i '' '16 s/^/; /g' $ini

# Enable extensions
for i in {54..79}
do
  command="sudo sed -i '' '$i s/; //g' $ini"
  eval="$command"
done

# Install .dotfiles
cd $HOME;
curl -sL $github/dotfiles/tarball/master | tar -xzv --strip-components 1 --exclude=readme.md

# Install command line
xcode-select --install

# Install Transmission
curl -O https://transmission.cachefly.net/Transmission-2.84.dmg | hdiutil attach Transmission-2.84.dmg | cp -R /Volumes/Transmission/Transmission.app /Applications/ | hdiutil detach /Volumes/Transmission | rm Transmission-2.84.dmg
