#!/usr/bin/env bash

# Ask for the administrator password upfront
sudo -v

###############################################################################
# PHP                                                                         #
###############################################################################

# Install PHP 5.6
curl -s http://php-osx.liip.ch/install.sh | bash -s 5.6

ini=/usr/local/php5/php.d/99-liip-developer.ini
github=https://github.com/mourawaldson

# Backup ini
sudo cp $ini $ini-bkp

# Change timezone
sudo sed -i '' 's/Zurich/Recife/g' $ini
sudo sed -i '' 's/Europe/America/g' $ini
sudo sed -i '' '15 s/^/; /g' $ini
sudo sed -i '' '16 s/^/; /g' $ini

# Enable extensions
for i in {54..79}
do
  command="sudo sed -i '' '$i s/; //g' $ini"
  eval="$command"
done

###############################################################################
# Apache                                                                      #
###############################################################################

# Define and create Sites dir
SITESDIR=/Users/mourawaldson/Sites
mkdir $SITESDIR

# Create info.php
PHPINFO="<?php
phpinfo();"
echo "$PHPINFO" > $SITESDIR/info.php

# Create user conf
MOURAWALDSONCONF="<Directory "$SITESDIR">
    Options Indexes FollowSymLinks MultiViews
    AllowOverride None
    Order allow,deny
    Allow from all
</Directory>"
echo "$MOURAWALDSONCONF" > /etc/apache2/users/mourawaldson.conf

# Make sure about user conf permission
sudo chmod 644 /etc/apache2/users/mourawaldson.conf

# Enable user conf
sudo sed -i '' 's/#Include\ \/private\/etc\/apache2\/extra\/httpd-userdir.conf/Include\ \/private\/etc\/apache2\/extra\/httpd-userdir.conf/g' /etc/apache2/httpd.conf

# Enable user conf dir
sudo sed -i '' 's/#Include\ \/private\/etc\/apache2\/users\/\*.conf/Include\ \/private\/etc\/apache2\/users\/\*.conf/g' /etc/apache2/extra/httpd-userdir.conf

# Enable user conf modules
sudo sed -i '' 's/#LoadModule\ authz_core_module\ libexec\/apache2\/mod_authz_core.so/LoadModule\ authz_core_module\ libexec\/apache2\/mod_authz_core.so/g' /etc/apache2/httpd.conf
sudo sed -i '' 's/#LoadModule\ authz_host_module\ libexec\/apache2\/mod_authz_host.so/LoadModule\ authz_host_module\ libexec\/apache2\/mod_authz_host.so/g' /etc/apache2/httpd.conf
sudo sed -i '' 's/#LoadModule\ userdir_module\ libexec\/apache2\/mod_userdir.so/LoadModule\ userdir_module\ libexec\/apache2\/mod_userdir.so/g' /etc/apache2/httpd.conf

# Enable PHP module
sudo sed -i '' 's/#LoadModule\ php5_module\ libexec\/apache2\/libphp5.so/LoadModule\ php5_module\ libexec\/apache2\/libphp5.so/g' /etc/apache2/httpd.conf

# Enable mod_rewrite module
sudo sed -i '' 's/#LoadModule\ rewrite_module\ libexec\/apache2\/mod_rewrite.so/LoadModule\ rewrite_module\ libexec\/apache2\/mod_rewrite.so/g' /etc/apache2/httpd.conf

# Enable vhosts conf
sudo sed -i '' 's/#Include\ \/private\/etc\/apache2\/extra\/httpd-vhosts.conf/Include\ \/private\/etc\/apache2\/extra\/httpd-vhosts.conf/g' /etc/apache2/httpd.conf

# Enable vhost alias module
sudo sed -i '' 's/#LoadModule\ vhost_alias_module\ libexec\/apache2\/mod_vhost_alias.so/LoadModule\ vhost_alias_module\ libexec\/apache2\/mod_vhost_alias.so/g' /etc/apache2/httpd.conf

# Add index.php as possible DirectoryIndex
sudo sed -i '' 's/DirectoryIndex\ index.html/DirectoryIndex\ index.html\ index.php/g' /etc/apache2/httpd.conf

# Restart Apache
sudo apachectl restart

# Start Apache automatically and Build most recent Apache
# https://gist.github.com/mourawaldson/f118948baebebe556dca

###############################################################################
# Apps                                                                        #
###############################################################################

# Git

# MySQL

# Google Chrome
curl -O https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg && hdiutil attach googlechrome.dmg && cp /Volumes/Google\ Chrome/Google\ Chrome.app /Applications/ && hdiutil detach /Volumes/Google\ Chrome && rm googlechrome.dmg

# Google Drive
curl -O https://dl.google.com/drive/installgoogledrive.dmg && hdiutil attach installgoogledrive.dmg && cp /Volumes/Install\ Google\ Drive/Google\ Drive.app /Applications/ && hdiutil detach /Volues/Install\ Google\ Drive && rm installgoogledrive.dmg

# CCleaner
curl -k -o ccleaner.dmg https://download.piriform.com/mac/CCMacSetup109.dmg && hdiutil attach ccleaner.dmg && cp -R /Volumes/CCleaner/CCleaner.app /Applications/ && hdiutil detach /Volumes/CCleaner && rm CCMacSetup109.dmg

# Transmission
curl -O https://transmission.cachefly.net/Transmission-2.84.dmg && hdiutil attach Transmission-2.84.dmg && cp -R /Volumes/Transmission/Transmission.app /Applications/ && hdiutil detach /Volumes/Transmission && rm Transmission-2.84.dmg

# VLC
curl -O http://mirror.csclub.uwaterloo.ca/vlc/vlc/2.2.0/macosx/vlc-2.2.0.dmg && hdiutil attach vlc-2.2.0.dmg && cp -R /Volumes/vlc-2.2.0/VLC.app /Applications/ && hdiutil detach /Volumes/vlc-2.2.0 && rm vlc-2.2.0.dmg

# DiffMerge
curl -o DiffMerge.dmg http://download-us.sourcegear.com/DiffMerge/4.2.0/DiffMerge.4.2.0.697.intel.stable.dmg && hdiutil attach DiffMerge.dmg && cp -R /Volumes/DiffMerge\ 4.2.0.697\ intel\ stable/DiffMerge.app /Applications/ && hdiutil detach /Volumes/DiffMerge\ 4.2.0.697\ intel\ stable && rm DiffMerge.dmg

# Atom
# Need to separate header and build a curl post
#curl -o atom https://atom.io/download/mac && url=$(grep -o "http.*\%3D" atom) && download=$(echo curl -o $url) && eval $download

# MacKeeper
curl -o MacKeeper.2.17.1.pkg http://download.mackeeper.com/package.php?bundleId=29_2 && open MacKeeper.2.17.1.pkg

# Dropbox
#https://www.dropbox.com/download?full=1&plat=mac

# GitHub
#https://central.github.com/mac/latest

# GitX
curl -O http://builds.phere.net/GitX/development/GitX-dev.dmg && hdiutil attach GitX-dev.dmg && cp -R /Volumes/GitX\ 1964/GitX.app /Applications/ && hdiutil detach /Volumes/GitX\ 1964 && rm GitX-dev.dmg

# Sequel Pro
curl -O https://sequel-pro.googlecode.com/files/sequel-pro-1.0.2.dmg && hdiutil attach sequel-pro-1.0.2.dmg && cp -R /Volumes/Sequel\ Pro\ 1.0.2/Sequel\ Pro.app /Applications/ && hdiutil detach /Volumes/Sequel\ Pro\ 1.0.2 && rm sequel-pro-1.0.2.dmg && cp ~/Dropbox/Softwares/Sequel\ Pro/Data/Favorites.plist ~/Library/Application\ Support/Sequel\ Pro/Data/Favorites.plist

###############################################################################
# Misc                                                                        #
###############################################################################

## Remember to install
# Hewlett-Packard  
# Microsoft Office 2011  

# Install command line
xcode-select --install

# Install .dotfiles
cd $HOME;
curl -sL $github/dotfiles/tarball/master | tar -xzv --strip-components 1 --exclude=readme.md && bash .dotfiles/install

# Install .osx
bash .dotfiles/.osx
